set -ex

# API keys: the judge (required -- it produces the reward) and the key-gated MCP servers.
# Real secrets belong in .env.mcp_atlas.local (gitignored); the committed .env.mcp_atlas
# holds placeholders only. Override with ENV_FILE=... to point elsewhere.
: "${ENV_FILE:=$(dirname "$0")/.env.mcp_atlas}"

# GRPO on MCP-Atlas via Harbor, reusing the existing Harbor entrypoint.
#
# Why this exists alongside run_mcp_atlas.sh: Harbor gives per-task container isolation,
# seeded state, and -- because the mcp-atlas agent collects per-turn token IDs and logprobs --
# step-wise training with off-policy correction, instead of re-tokenizing a finished
# conversation. run_mcp_atlas.sh remains the lighter path (one shared sandbox, no Harbor).
#
# Prerequisites:
#   1. The harbor dependency must include the mcp-atlas agent:
#        pyproject.toml -> harbor = { git = ".../AfterQuery/harbor-aq", rev/branch = "aq" }
#      On upstream Harbor, `agent.name: mcp-atlas` is unknown and trials fail immediately.
#   2. Task bundles generated by the adapter:
#        cd /path/to/harbor/adapters/mcp_atlas
#        uv run run_adapter.py --hf --image <mcp-image> --mcp-url http://localhost:1984/mcp \
#          --out $HOME/data/mcp_atlas_harbor/tasks
#   3. A judge for the verifier:
#        export EVAL_LLM_BASE_URL=... EVAL_LLM_API_KEY=... EVAL_LLM_MODEL=...
#   4. export WANDB_API_KEY=<key>

DATA_DIR="${DATA_DIR:-$HOME/data/mcp_atlas_harbor/tasks}"
TRAIN_DATA="['$DATA_DIR']"

RUN_NAME="mcp_atlas_harbor"
STORAGE_ROOT="$HOME/mcp_atlas_harbor_run"
TRIAL_CONFIG="$(dirname "$0")/harbor_trial_config.yaml"

# Interleaved thinking + strictly-appending history, which is what makes step-wise
# prefix merging effective. Same template the codecontest example uses.
CHAT_TEMPLATE_PATH="$(dirname "$0")/../../../skyrl/train/utils/templates/qwen3_acc_thinking.jinja2"

MAX_MODEL_LEN=32768
N_SAMPLES_PER_PROMPT=8
TRAIN_BATCH_SIZE=8
NUM_POLICY_GPUS=8
NUM_INFERENCE_ENGINES=4
TP_SIZE=2

# NOTE: deliberately NO enable_auto_tool_choice / tool_call_parser here. The mcp-atlas agent
# sends tool_choice="none" and reads <tool_call>{...}</tool_call> from the response text,
# because Harbor's LLMResponse has no tool_calls field. vLLM rejects tools= under the default
# "auto" unless those flags are set, and setting them makes its parser strip the calls out of
# `content`. tool_choice="none" still renders every schema into the prompt (Qwen templates
# ignore tool_choice), so the model emits the same tokens either way -- the parser is a regex
# over the completion, not a change in model behaviour.
uv run --isolated --extra fsdp --extra harbor --env-file "$ENV_FILE" \
  -m examples.train_integrations.harbor.entrypoints.main_harbor \
  data.train_data="$TRAIN_DATA" \
  trainer.policy.model.path=Qwen/Qwen3-8B \
  generator.inference_engine.served_model_name=Qwen3-8B \
  harbor_trial_config="$(cat "$TRIAL_CONFIG" | python3 -c 'import sys,yaml,json; print(json.dumps(yaml.safe_load(sys.stdin)))')" \
  trainer.export_path="$STORAGE_ROOT/exports" \
  trainer.ckpt_path="$STORAGE_ROOT/ckpts" \
  trainer.log_path="$STORAGE_ROOT/logs" \
  trainer.algorithm.advantage_estimator=grpo \
  trainer.algorithm.loss_reduction=token_mean \
  trainer.algorithm.grpo_norm_by_std=false \
  trainer.algorithm.use_kl_loss=false \
  trainer.algorithm.max_seq_len=$MAX_MODEL_LEN \
  trainer.algorithm.off_policy_correction.tis_ratio_type=token \
  trainer.placement.colocate_all=true \
  trainer.strategy=fsdp \
  trainer.placement.policy_num_gpus_per_node=$NUM_POLICY_GPUS \
  trainer.placement.ref_num_gpus_per_node=$NUM_POLICY_GPUS \
  generator.inference_engine.num_engines=$NUM_INFERENCE_ENGINES \
  generator.inference_engine.tensor_parallel_size=$TP_SIZE \
  generator.inference_engine.engine_init_kwargs.max_model_len=$MAX_MODEL_LEN \
  generator.inference_engine.engine_init_kwargs.chat_template=$CHAT_TEMPLATE_PATH \
  generator.inference_engine.backend=vllm \
  generator.inference_engine.run_engines_locally=true \
  generator.inference_engine.weight_sync_backend=nccl \
  generator.inference_engine.gpu_memory_utilization=0.8 \
  generator.batched=false \
  generator.step_wise_trajectories=true \
  generator.merge_stepwise_output=true \
  generator.n_samples_per_prompt=$N_SAMPLES_PER_PROMPT \
  trainer.train_batch_size=$TRAIN_BATCH_SIZE \
  trainer.policy_mini_batch_size=$TRAIN_BATCH_SIZE \
  trainer.micro_forward_batch_size_per_gpu=1 \
  trainer.micro_train_batch_size_per_gpu=1 \
  trainer.epochs=3 \
  trainer.logger=wandb \
  trainer.project_name=mcp_atlas_harbor \
  trainer.run_name=$RUN_NAME \
  "$@"
